src/main/java/acme/entities/Chirp.java
Creada la entidad Chip con sus atributos.
=> Task-07: Crear la entidad Chirp

src/main/java/acme/entities/Component.java
Creada la entidad Componente y sus respectivos atributos.
=> Task-09: crear la entidad Componente

src/main/java/acme/entities/Chirp.java
Corrección de atributo creationMoment y eliminadas redundancias.
=> Corrección de errores en la entidad Chirp

src/main/java/acme/entities/Item.java, src/main/java/acme/entities/ItemType.java, src/main/java/acme/entities/Quantity.java
Para crear ambas entidades, se ha eliminado la entidad componente previa
y se han unido componente y tool en Item, siendo ItemType el enumerado
que contiene COMPONENT y TOOL. Además se ha creado la entidad quantity
para expresar la cantidad de cada item.
=> Task-09 y Task-10: crear entidades Component y Tool

reports/model.uxf, src/main/java/acme/entities/Announcement.java, src/main/java/acme/entities/Patronage.java
Además, se incluye una modificación de Announcement para incluir el
serialVersionUID y eliminar redundancias y una modificación en Patronage
para corregir una notación sobre Money.
=> Task-18: Avances en el modelo UML

src/main/java/acme/forms/PatronDashboard.java
Se ha cambiado los Integer y Double en Maps para aumentar la facilidad
en los siguientes deliverables
=> Cambios de atributos en PatronDashboard

src/main/java/acme/forms/AdminDashboard.java, src/main/java/acme/forms/PatronDashboard.java
Se ha incluido algunos atributos que faltaban y se ha modificado todos los atributos a Maps.
=> Varios fixes a AdminDashboard

reports/model.uxf
Actualizado el nombre del atributo de la entidad Quantity, actualizada
la entidad Patronage añadiendo notación NotNull a status y arreglando
budget añadiendo un comentario, creada la entidad SystemConfiguration y
actualizadas las relaciones para indicar origen.
=> Task-18: Actualización del modelo

src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementController.java, src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementListRecentService.java, src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementRepository.java, src/main/java/acme/features/authenticated/announcement/AuthenticatedAnnouncementShowService.java, src/main/webapp/WEB-INF/views/authenticated/announcement/form.jsp, src/main/webapp/WEB-INF/views/authenticated/announcement/list.jsp, src/main/webapp/WEB-INF/views/authenticated/announcement/messages-en.i18n, src/main/webapp/WEB-INF/views/authenticated/announcement/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
=> No funciona pero es lo que llevo hecho y no altera lo que si es

src/main/java/acme/features/any/chirp/AnyChirpController.java, src/main/java/acme/features/any/chirp/AnyChirpListService.java, src/main/java/acme/features/any/chirp/AnyChirpRepository.java, src/main/webapp/WEB-INF/resources/sample-data/chirp.csv, src/main/webapp/WEB-INF/views/any/chirp/list.jsp, src/main/webapp/WEB-INF/views/any/chirp/messsages-en.i18n, src/main/webapp/WEB-INF/views/any/chirp/messsages-es.i18n
Task-23: operations by all principals on chirps done.
=> Task-23: Done

src/main/java/acme/features/any/item/AnyItemController.java, src/main/java/acme/features/any/item/AnyItemListComponentService.java, src/main/java/acme/features/any/item/AnyItemRepository.java, src/main/java/acme/features/any/item/AnyItemShowService.java, src/main/webapp/WEB-INF/views/any/item/form.jsp, src/main/webapp/WEB-INF/views/any/item/list.jsp, src/main/webapp/WEB-INF/views/any/item/messsages-en.i18n, src/main/webapp/WEB-INF/views/any/item/messsages-es.i18n
Task-24: operations by all principals on components done.
=> Task-24: Done

src/main/java/acme/features/inventor/toolkit/InventorToolKitController.java, src/main/java/acme/features/inventor/toolkit/InventorToolKitListService.java, src/main/java/acme/features/inventor/toolkit/InventorToolKitRepository.java, src/main/java/acme/features/inventor/toolkit/InventorToolKitShowService.java, src/main/webapp/WEB-INF/views/inventor/tool-kit/form.jsp, src/main/webapp/WEB-INF/views/inventor/tool-kit/list.jsp, src/main/webapp/WEB-INF/views/inventor/tool-kit/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/tool-kit/messsages-es.i18n
Ya es posible ver las toolkits asociadas a un inventor y sus detalles (a falta de modificar el link del botón de los detalles una vez que inventor/item este realizado)
=> Task 31: Done

src/main/java/acme/features/any/item/AnyItemController.java, src/main/java/acme/features/any/item/AnyItemListComponentService.java, src/main/java/acme/features/any/item/AnyItemListToolService.java, src/main/java/acme/features/any/item/AnyItemRepository.java
Task-25: Operations by all principals on tools.
=> Task-25: Done

src/main/java/acme/features/patron/patronageReport/PatronPatronageReportController.java, src/main/java/acme/features/patron/patronageReport/PatronPatronageReportListService.java, src/main/java/acme/features/patron/patronageReport/PatronPatronageReportRepository.java, src/main/java/acme/features/patron/patronageReport/PatronPatronageReportShowService.java, src/main/webapp/WEB-INF/views/patron/patronage-report/form.jsp, src/main/webapp/WEB-INF/views/patron/patronage-report/list.jsp, src/main/webapp/WEB-INF/views/patron/patronage-report/messsages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage-report/messsages-es.i18n
Ya es posible ver los patronageReport asociados a un patron y sus detalles
=> Task 35: Done

src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/list.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage/messsages-es.i18n
Por alguna razón no están en master y no me deja subirlas desde la rama
de su rama especifica (Task-32)
=> Subida de las vistas de inventor/patronage

src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
(A falta de los links de los dashboard)
=> Actualizado menu con las opciones

src/main/java/acme/features/inventor/patronage/InventorPatronageController.java, src/main/java/acme/features/inventor/patronage/InventorPatronageListService.java, src/main/java/acme/features/inventor/patronage/InventorPatronageRepository.java, src/main/java/acme/features/inventor/patronage/InventorPatronageShowService.java, src/test/java/acme/testing/any/chirp/AnyChirpListTest.java, src/test/java/acme/testing/any/item/AnyItemComponentListShowTest.java, src/test/java/acme/testing/any/item/AnyItemToolListShowTest.java, src/test/resources/any/chirp/list.csv, src/test/resources/any/item/list-component.csv, src/test/resources/any/item/list-tool.csv
=> Task 43: en progreso

src/test/java/acme/testing/any/userAccount/AnyUserAccountListShowTest.java, src/test/resources/any/userAccount/list.csv
=> Task-45: In progress.

.settings/org.eclipse.wst.common.component, pom.xml, src/main/webapp/WEB-INF/views/fragments/banner-en.i18n, src/main/webapp/WEB-INF/views/fragments/banner-es.i18n, src/main/webapp/WEB-INF/views/fragments/company-en.i18n, src/main/webapp/WEB-INF/views/fragments/company-es.i18n, src/main/webapp/WEB-INF/views/fragments/title-en.i18n, src/main/webapp/WEB-INF/views/fragments/title-es.i18n
Algunas actualizaciones de nombres
=> Actualizaciones del nombre

src/test/java/acme/testing/authenticated/announcement/AuthenticatedAnnouncementListShowTest.java, src/test/java/acme/testing/inventor/item/InventorItemComponentListShowTest.java, src/test/java/acme/testing/inventor/item/InventorItemToolListShowTest.java, src/test/resources/authenticated/announcement/list.csv, src/test/resources/inventor/item/list-component.csv, src/test/resources/inventor/item/list-tool.csv
Test of Task-29 and Task-30 done. Test of Task-27 has errors.
=> Task-50: in progress

src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardController.java, src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardRepository.java, src/main/java/acme/features/administrator/adminDashboard/AdministradorAdminDashboardShowService.java, src/main/java/acme/forms/AdminDashboard.java, src/main/webapp/WEB-INF/views/administrator/admin-dashboard/form.jsp, src/main/webapp/WEB-INF/views/administrator/admin-dashboard/messages-en.i18n, src/main/webapp/WEB-INF/views/administrator/admin-dashboard/messages-es.i18n
Ya es posible ver las métricas asociadas al Dashboard de admins
=> Task 38: Done

src/main/java/acme/features/patron/patronageReport/PatronPatronageReportShowService.java
Restringido acceso reportes de patrocinio que no pertenecen a un patron
=> Fixes Task-35

reports/model.uxf, src/main/java/acme/entities/Item.java, src/main/java/acme/features/any/item/AnyItemListComponentService.java, src/main/java/acme/features/any/item/AnyItemListToolService.java, src/main/java/acme/features/any/item/AnyItemRepository.java, src/main/java/acme/features/any/item/AnyItemShowService.java, src/main/webapp/WEB-INF/resources/sample-data/item.csv, src/main/webapp/WEB-INF/views/any/item/form.jsp, src/main/webapp/WEB-INF/views/any/item/list.jsp, src/main/webapp/WEB-INF/views/any/item/messsages-en.i18n, src/main/webapp/WEB-INF/views/any/item/messsages-es.i18n
Ahora sólo se muestran los componentes y herramientas publicadas.
Además, sólo se puede acceder al show de las publicadas.
=> Task-24 & Task-25: Done

src/main/java/acme/entities/ToolKit.java, src/main/java/acme/features/inventor/toolkit/InventorToolKitRepository.java, src/main/java/acme/features/inventor/toolkit/InventorToolKitShowService.java, src/main/webapp/WEB-INF/resources/sample-data/tool-kit.csv, src/main/webapp/WEB-INF/views/inventor/tool-kit/form.jsp, src/main/webapp/WEB-INF/views/inventor/tool-kit/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/tool-kit/messsages-es.i18n
Tambien se ha modificado los botones de la vista show y añadido el
atributo inventor para identificar que toolkits estan asociadas a sus
inventores
=> InventorToolkits restricción visualizar detalles si eres su inventor

src/main/java/acme/features/patron/patronDashboard/PatronPatronDashboardController.java, src/main/java/acme/features/patron/patronDashboard/PatronPatronDashboardRepository.java, src/main/java/acme/features/patron/patronDashboard/PatronPatronDashboardShowService.java, src/main/java/acme/forms/PatronDashboard.java, src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp, src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n, src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Ya es posible visualizar las metricas de PatronDashboard
=> Creado Controlador, Servicio, Repositorio y vista de PatronDashboard

reports/model.uxf
Se han modificado los tipos de los metodos de los dashboard, se ha
añadido una nueva relación entre toolkit e inventor y se ha añadido Any
=> Modificado model.uxf

src/test/java/acme/testing/inventor/item/InventorItemComponentListShowTest.java, src/test/java/acme/testing/inventor/item/InventorItemToolListShowTest.java, src/test/resources/inventor/item/list-component.csv, src/test/resources/inventor/item/list-tool.csv
Fixed errors in tests related to changes in master.
=> Task-50: Test of Task-29 and Task-30 Done

src/test/java/acme/testing/authenticated/systemConfiguration/AuthenticatedSystemConfigurationShowTest.java, src/test/resources/authenticated/systemConfiguration/show.csv
Creado test para System Configuration(Authenticated)
=> Task-47: Done

src/main/java/acme/features/inventor/item/InventorComponentListService.java, src/main/java/acme/features/inventor/item/InventorItemController.java, src/main/java/acme/features/inventor/item/InventorItemCreateService.java, src/main/java/acme/features/inventor/item/InventorItemDeleteService.java, src/main/java/acme/features/inventor/item/InventorItemPublishService.java, src/main/java/acme/features/inventor/item/InventorItemRepository.java, src/main/java/acme/features/inventor/item/InventorItemUpdateService.java, src/main/webapp/WEB-INF/views/inventor/item/form.jsp, src/main/webapp/WEB-INF/views/inventor/item/list.jsp, src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
Operaciones de Inventors sobre Components y Tools implementadas junto a
sus restricciones.
=> Task-54: Done

src/main/java/acme/features/any/chirp/AnyChirpController.java, src/main/java/acme/features/any/chirp/AnyChirpCreateService.java, src/main/webapp/WEB-INF/views/any/chirp/form.jsp, src/main/webapp/WEB-INF/views/any/chirp/list.jsp, src/main/webapp/WEB-INF/views/any/chirp/messsages-en.i18n, src/main/webapp/WEB-INF/views/any/chirp/messsages-es.i18n
Creación de chirp implementada, falta que el sistema pida confirmación
antes de crear.
=> Task-53: Almost Done

src/main/java/acme/features/administrator/announcement/AdministratorAnnouncementController.java, src/main/java/acme/features/administrator/announcement/AdministratorAnnouncementCreateService.java, src/main/java/acme/features/administrator/announcement/AdministratorAnnouncementRepository.java, src/main/webapp/WEB-INF/views/administrator/announcement/form.jsp, src/main/webapp/WEB-INF/views/administrator/announcement/messages-en.i18n, src/main/webapp/WEB-INF/views/administrator/announcement/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
Ya es posible la creación de anuncios por parte de los administradores.
=> Task-59: Done

src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorController.java, src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorCreateService.java, src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorRepository.java, src/main/java/acme/features/authenticated/inventor/AuthenticatedInventorUpdateService.java, src/main/java/acme/features/authenticated/patron/AuthenticatedPatronController.java, src/main/java/acme/features/authenticated/patron/AuthenticatedPatronCreateService.java, src/main/java/acme/features/authenticated/patron/AuthenticatedPatronRepository.java, src/main/java/acme/features/authenticated/patron/AuthenticatedPatronUpdateService.java, src/main/webapp/WEB-INF/views/authenticated/inventor/form.jsp, src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-en.i18n, src/main/webapp/WEB-INF/views/authenticated/inventor/messsages-es.i18n, src/main/webapp/WEB-INF/views/authenticated/patron/form.jsp, src/main/webapp/WEB-INF/views/authenticated/patron/messsages-en.i18n, src/main/webapp/WEB-INF/views/authenticated/patron/messsages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
Operaciones de anónimos sobre cuentas de usuario hechas.
=> Task-69: Done

reports/model.uxf, src/main/java/acme/entities/Patronage.java, src/main/java/acme/features/inventor/patronage/InventorPatronageListService.java, src/main/java/acme/features/inventor/patronage/InventorPatronageShowService.java, src/main/java/acme/features/patron/patronage/PatronPatronageController.java, src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronageDeleteService.java, src/main/java/acme/features/patron/patronage/PatronPatronageListService.java, src/main/java/acme/features/patron/patronage/PatronPatronagePublishService.java, src/main/java/acme/features/patron/patronage/PatronPatronageRepository.java, src/main/java/acme/features/patron/patronage/PatronPatronageShowService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java, src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/list.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage/messsages-es.i18n, src/main/webapp/WEB-INF/views/patron/patronage/form.jsp, src/main/webapp/WEB-INF/views/patron/patronage/list.jsp, src/main/webapp/WEB-INF/views/patron/patronage/messsages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage/messsages-es.i18n
Ya es posible la creación, actualización, borrado y publicación de patrocinios por parte de los patrocinadores.
=> Task-58: Done

src/main/java/acme/features/inventor/item/InventorItemCreateService.java, src/main/java/acme/features/inventor/item/InventorItemPublishService.java, src/main/java/acme/features/inventor/item/InventorItemRepository.java, src/main/java/acme/features/inventor/item/InventorItemUpdateService.java, src/main/webapp/WEB-INF/views/inventor/item/form.jsp, src/main/webapp/WEB-INF/views/inventor/item/messsages-en.i18n, src/main/webapp/WEB-INF/views/inventor/item/messsages-es.i18n
Corrección de publish en el formulario para que no se pueda publicar con
update. Correción de restricciones al crear, actualizar y publicar items
relacionadas con el campo retailPrice.
=> Task-54: Fix

src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronageDeleteService.java, src/main/java/acme/features/patron/patronage/PatronPatronagePublishService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java, src/main/webapp/WEB-INF/views/patron/patronage/form.jsp, src/main/webapp/WEB-INF/views/patron/patronage/messsages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage/messsages-es.i18n
Se ha actualizado la funcionalidades de los patrocinios por parte de
patrón para que el botón de publicar solo publique el patrocinio y se ha
ajustado la creación y la modificación para que no exista la posibilidad
de que solo se pueda escoger el estatus de "Proposed"
=> Task-58: Fix

src/test/java/acme/testing/inventor/patronage/InventorPatronageUpdateTest.java, src/test/java/acme/testing/inventor/patronageReport/InventorPatronageReportCreateTest.java, src/test/resources/inventor/patronage-report/create-negative.csv, src/test/resources/inventor/patronage-report/create-positive.csv, src/test/resources/inventor/patronage/update-positive.csv
Se han creado los test relacionados para las Task-56 y Task-57
=> Task-74: Done

src/test/java/acme/testing/patron/patronage/PatronPatronageCreateTest.java
Había varios tests comentados, por lo que se ha procedido a
descomentarlos
=> Varios test descomentados
